<template>
    <AuthenticatedLayout title="Warehouse Monthly Report" description="Monthly Inventory Movement Summary" img="/assets/images/report.png">
        <Head title="Warehouse Monthly Report" />
        
        <!-- Header Section -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
            <div class="flex items-center space-x-3 mb-6">
                <div class="flex items-center justify-center w-10 h-10 bg-green-100 rounded-lg">
                    <svg class="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v4a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                </div>
                <div>
                    <h1 class="text-lg font-semibold text-gray-900">Warehouse Monthly Inventory Report</h1>
                    <p class="text-xs text-gray-600">Monthly inventory movement summary with balances and transactions</p>
                </div>
            </div>

            <!-- Report Status -->
            <div v-if="inventoryReport" class="mb-6 p-4 bg-gray-50 rounded-lg border">
                <div class="flex items-center justify-between mb-4">
                    <div>
                        <h3 class="text-xs font-medium text-gray-900 mb-1">Report Status</h3>
                        <div class="space-y-2">
                            <span :class="getStatusBadgeClass(inventoryReport.status)" class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
                                {{ getStatusText(inventoryReport.status) }}
                            </span>
                            <div v-if="inventoryReport.status === 'rejected'" class="mt-2">
                                <h4 class="text-xs font-medium text-gray-700 mb-1">Rejection Reason</h4>
                                <p class="text-xs text-gray-600 whitespace-pre-wrap">{{ inventoryReport.rejection_reason }}</p>
                            </div>
                            <div class="mt-2">
                                <h4 class="text-xs font-medium text-gray-700 mb-1">Report Timeline</h4>
                                <ul class="space-y-2">
                                    <li v-if="inventoryReport.generated_at" class="flex items-center text-xs text-gray-600">
                                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/>
                                        </svg>
                                        Generated by {{ inventoryReport.generated_by?.name }} on {{ formatDate(inventoryReport.generated_at) }}
                                    </li>
                                    <li v-if="inventoryReport.submitted_at" class="flex items-center text-xs text-gray-600">
                                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                        </svg>
                                        Submitted by {{ inventoryReport.submitted_by?.name }} on {{ formatDate(inventoryReport.submitted_at) }}
                                    </li>
                                    <li v-if="inventoryReport.reviewed_at" class="flex items-center text-xs text-gray-600">
                                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                                        </svg>
                                        Reviewed by {{ inventoryReport.reviewed_by?.name }} on {{ formatDate(inventoryReport.reviewed_at) }}
                                    </li>
                                    <li v-if="inventoryReport.approved_at" class="flex items-center text-xs text-gray-600">
                                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                                        </svg>
                                        Approved by {{ inventoryReport.approved_by?.name }} on {{ formatDate(inventoryReport.approved_at) }}
                                    </li>
                                    <li v-if="inventoryReport.rejected_at" class="flex items-center text-xs text-gray-600">
                                        <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                                        </svg>
                                        Rejected by {{ inventoryReport.rejected_by?.name }} on {{ formatDate(inventoryReport.rejected_at) }}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="flex space-x-2">
                        <!-- Submit Button -->
                        <button 
                            v-if="canSubmit"
                            @click="submitReport"
                            :disabled="processing"
                            class="inline-flex items-center px-3 py-2 border border-transparent text-xs leading-4 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:opacity-50"
                        >
                            Submit for Review
                        </button>

                        <!-- Review Button -->
                        <button 
                            v-if="canReview && inventoryReport.status === 'submitted'"
                            @click="reviewReport"
                            :disabled="processing"
                            class="inline-flex items-center px-3 py-2 border border-transparent text-xs leading-4 font-medium rounded-md text-white bg-yellow-600 hover:bg-yellow-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500 disabled:opacity-50"
                        >
                            Start Review
                        </button>

                        <!-- Approve Button -->
                        <button 
                            v-if="canApprove"
                            @click="approveReport"
                            :disabled="processing"
                            class="inline-flex items-center px-3 py-2 border border-transparent text-xs leading-4 font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 disabled:opacity-50"
                        >
                            Approve
                        </button>

                        <!-- Reject Button -->
                        <button 
                            v-if="canReject"
                            @click="rejectReport"
                            :disabled="processing"
                            class="inline-flex items-center px-3 py-2 border border-gray-300 text-xs leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
                        >
                            Reject
                        </button>
                    </div>
                </div>
            </div>

            <!-- Filters -->
            <div class="flex justify-between mb-[30px]">
                <!-- Month Filter -->
                <div class="w-[200px]">
                    <label for="month" class="block text-xs font-medium text-gray-700 mb-2">
                        <svg class="w-4 h-4 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                        Report Month
                    </label>
                    <input 
                        type="month" 
                        id="month"
                        v-model="month_year" 
                        class="block w-full px-3 py-2.5 border border-gray-300 rounded-lg bg-gray-50 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 focus:bg-white transition-colors duration-200 text-xs"
                    />
                </div>



            </div>

            <!-- Success/Error Messages -->
            <div v-if="$page.props.flash.success" class="mb-6 bg-green-50 border border-green-200 rounded-lg p-4">
                <div class="flex items-center">
                    <svg class="w-5 h-5 text-green-600 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                    </svg>
                    <p class="text-green-800 text-xs font-medium">{{ $page.props.flash.success }}</p>
                </div>
            </div>

            <div v-if="$page.props.flash.error" class="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
                <div class="flex items-center">
                    <svg class="w-5 h-5 text-red-600 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    <p class="text-red-800 text-xs font-medium">{{ $page.props.flash.error }}</p>
                </div>
            </div>

            <!-- Report Table -->
            <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden mb-[80px]">
                <!-- Table Header -->
                <div class="px-6 py-4 border-b border-gray-200 bg-gray-50">
                    <h2 class="text-xs font-semibold text-gray-900">Items</h2>
                    <p class="text-xs text-gray-600 mt-1">{{ formatMonthYear(month_year) }}</p>
                </div>

                <div v-if="reportData?.length > 0" class="overflow-x-auto">
                    <table class="w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="p-2 text-left text-xs text-black capitalize tracking-wider">
                                    Item
                                </th>
                                <th scope="col" class="p-2 text-left text-xs text-black capitalize tracking-wider">
                                    UoM
                                </th>
                                <th scope="col" class="p-2 text-left text-xs text-black capitalize tracking-wider">
                                    Expiry Date
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Beginning Balance
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Stock Received
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Stock Issued
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Positive Adj.
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Negative Adj.
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Closing Balance
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Unit Cost
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Total Cost
                                </th>
                                <th scope="col" class="p-2 text-right text-xs text-black capitalize tracking-wider">
                                    Months of Stock
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                            <tr v-for="item in reportData" :key="item.product.id" class="hover:bg-gray-50 transition-colors duration-150">
                                <td class="p-2">
                                    <div class="flex items-center space-x-3">
                                        <div class="min-w-0 flex-1">
                                            <p class="text-xs font-medium text-gray-900 truncate">
                                                {{ item.product.name }}
                                            </p>
                                            <p class="text-xs text-gray-500 truncate">
                                                {{ item.product.category?.name || 'Uncategorized' }} • 
                                                {{ item.product.dosage?.name || 'No dosage' }}
                                            </p>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                   {{ item.uom }}
                                </td>
                                <td>
                                   {{ formatDate(item.expiry_date) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-gray-900">
                                    {{ formatNumber(item.beginning_balance) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-green-600">
                                    {{ formatNumber(item.received_quantity) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-red-600">
                                    {{ formatNumber(item.issued_quantity) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-blue-600">
                                    <div v-if="canEdit" class="relative">
                                        <input 
                                            type="text" 
                                            :value="getCurrentAdjustment(item.product.id, 'positive_adjustment')"
                                            @keyup.enter="updateAdjustment(item.product.id, 'positive_adjustment', $event.target.value, $event)"
                                            class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                        />
                                        <div v-if="cellLoading[item.product.id]?.positive_adjustment" 
                                             class="absolute right-2 top-1/2 -translate-y-1/2 text-blue-500">
                                            <svg class="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <span v-else>{{ formatNumber(item.positive_adjustment) }}</span>
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-orange-600">
                                    <div v-if="canEdit" class="relative">
                                        <input 
                                            type="text" 
                                            :value="getCurrentAdjustment(item.product.id, 'negative_adjustment')"
                                            @input="updateAdjustment(item.product.id, 'negative_adjustment', $event.target.value, $event)"
                                            class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                        />
                                        <div v-if="cellLoading[item.product.id]?.negative_adjustment" 
                                             class="absolute right-2 top-1/2 -translate-y-1/2 text-blue-500">
                                            <svg class="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <span v-else>{{ formatNumber(item.negative_adjustment) }}</span>
                                </td>
                                <td class="p-2 text-right text-xs font-bold" :class="item.closing_balance > 0 ? 'text-green-600' : item.closing_balance < 0 ? 'text-red-600' : 'text-gray-600'">
                                    {{ formatNumber(item.closing_balance) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-gray-900">
                                    {{ formatNumber(item.unit_cost) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-gray-900">
                                    {{ formatNumber(item.total_cost) }}
                                </td>
                                <td class="p-2 text-right text-xs font-medium text-gray-900">
                                    <div v-if="canEdit" class="relative">
                                        <input 
                                            type="text" 
                                            :value="getCurrentAdjustment(item.product.id, 'months_of_stock')"
                                            @input="updateAdjustment(item.product.id, 'months_of_stock', $event.target.value, $event)"
                                            class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                                        />
                                        <div v-if="cellLoading[item.product.id]?.months_of_stock" 
                                             class="absolute right-2 top-1/2 -translate-y-1/2 text-blue-500">
                                            <svg class="animate-spin h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                                                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <span v-else class="text-xs">{{ formatNumber(item.months_of_stock) }}</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- Empty State -->
                <div v-else class="text-center py-12">
                    <div class="flex justify-center mb-4">
                        <div class="flex items-center justify-center w-16 h-16 bg-gray-100 rounded-full">
                            <svg class="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                            </svg>
                        </div>
                    </div>
                    <h3 class="text-xs font-medium text-gray-900 mb-2">No data available</h3>
                    <p class="text-xs text-gray-500 mb-4">No inventory movements found for the selected month.</p>
                </div>

            </div>
        </div>
        <!-- ... -->
    </AuthenticatedLayout>
</template>

<script setup>
    import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
    import { Head, Link, router } from '@inertiajs/vue3';
    import { ref, computed, watch, onMounted } from 'vue';
    import axios from 'axios';
    import Swal from 'sweetalert2';
    import moment from 'moment';

    const props = defineProps({
        reportData: {
            type: Array,
            default: () => []
        },
        filters: {
            type: Object,
            default: () => ({})
        },
        inventoryReport: {
            type: Object,
            default: () => ({})
        }
    });
    const currentAdjustments = ref({});
    const originalAdjustments = ref({});
    const month_year = ref(props.filters.month_year);
    const cellLoading = ref({});

    // Initialize cell loading states
    onMounted(() => {
        props.reportData.forEach(item => {
            cellLoading.value[item.product.id] = {
                positive_adjustment: false,
                negative_adjustment: false,
                months_of_stock: false
            };
        });
    });
    const processing = ref(false);
    const saving = ref(false);



    watch([
        () => month_year.value,
    ], () => {
        reloadData();
    });

    // Initialize adjustments when component is mounted
    onMounted(() => {
        initializeAdjustments();
    });

    function reloadData(){
        const query = {}
        if(month_year.value) query.month_year = month_year.value
        router.get(route('reports.warehouseMonthly', query, {
            preserveState: true,
            preserveScroll: true,
            only: [
                'reportData'
            ]
        }))
    }
    // Safe getter for adjustment values
    const getCurrentAdjustment = (productId, field) => {
        if (!currentAdjustments.value[productId]) {
            return 0; // Return default value if not initialized
        }
        return currentAdjustments.value[productId][field] || 0;
    };

    // Initialize adjustments tracking
    const initializeAdjustments = () => {
        if (props.reportData && Array.isArray(props.reportData)) {
            const newOriginal = {};
            const newCurrent = {};
            
            props.reportData.forEach(item => {
                if (!item.product?.id) return; // Skip if no product id
                
                // Initialize with default values if any field is undefined
                newOriginal[item.product.id] = {
                    positive_adjustment: item.positive_adjustment ?? 0,
                    negative_adjustment: item.negative_adjustment ?? 0,
                    months_of_stock: item.months_of_stock?.toString() ?? '0'  // Convert to string
                };
                
                newCurrent[item.product.id] = {
                    positive_adjustment: item.positive_adjustment ?? 0,
                    negative_adjustment: item.negative_adjustment ?? 0,
                    months_of_stock: item.months_of_stock?.toString() ?? '0'  // Convert to string
                };
            });
            
            originalAdjustments.value = newOriginal;
            currentAdjustments.value = newCurrent;
        }
    };

    // format dates
    const formatDate = (date) => {
        return moment(date).format('DD/MM/YYYY');
    };

    // Computed properties
    const canEdit = computed(() => {
        return props.inventoryReport?.status === 'generated' || props.inventoryReport?.status === 'rejected';
    });

    const submittedBy = computed(() => {
        return props.inventoryReport?.submitted_by ? props.inventoryReport.submitted_by.name : null;
    });

    const reviewedBy = computed(() => {
        return props.inventoryReport?.reviewed_by ? props.inventoryReport.reviewed_by.name : null;
    });

    const approvedBy = computed(() => {
        return props.inventoryReport?.approved_by ? props.inventoryReport.approved_by.name : null;
    });

    const rejectedBy = computed(() => {
        return props.inventoryReport?.rejected_by ? props.inventoryReport.rejected_by.name : null;
    });

    const canSubmit = computed(() => {
        return props.inventoryReport?.status === 'generated' || props.inventoryReport?.status === 'rejected';
    });

    const canReview = computed(() => {
        return props.inventoryReport?.status === 'submitted';
    });

    const canApprove = computed(() => {
        return props.inventoryReport?.status === 'under_review';
    });

    const canReject = computed(() => {
        return props.inventoryReport?.status === 'under_review';
    });

    const hasUnsavedChanges = computed(() => {
        if (!currentAdjustments.value || !originalAdjustments.value) {
            return false;
        }

        return Object.keys(currentAdjustments.value).some(id => {
            const current = currentAdjustments.value[id];
            const original = originalAdjustments.value[id];
            
            // Return false if either current or original is undefined
            if (!current || !original) {
                return false;
            }

            return current.positive_adjustment !== original.positive_adjustment ||
                   current.negative_adjustment !== original.negative_adjustment ||
                   current.months_of_stock !== original.months_of_stock;
        });
    });

    // Format month year for display
    const formatMonthYear = (dateString) => {
        if (!dateString) return 'Select Month';
        return moment(dateString).format('MMMM YYYY');
    };

    // Format numbers with commas
    const formatNumber = (num) => {
        if (num === null || num === undefined) return '0';
        return Number(num).toLocaleString();
    };

    // Get balance color based on value
    const getBalanceColor = (balance) => {
        if (balance > 0) return 'text-green-600';
        if (balance < 0) return 'text-red-600';
        return 'text-gray-600';
    };

    // Get status badge class
    const getStatusBadgeClass = (status) => {
        switch (status) {
            case 'generated':
                return 'bg-yellow-100 text-yellow-800';
            case 'submitted':
                return 'bg-blue-100 text-blue-800';
            case 'under_review':
                return 'bg-purple-100 text-purple-800';
            case 'approved':
                return 'bg-green-100 text-green-800';
            case 'rejected':
                return 'bg-red-100 text-red-800';
            default:
                return 'bg-gray-100 text-gray-800';
        }
    };

    // Get status text
    const getStatusText = (status) => {
        switch (status) {
            case 'generated':
                return 'Draft';
            case 'submitted':
                return 'Submitted for Review';
            case 'under_review':
                return 'Under Review';
            case 'approved':
                return 'Approved';
            case 'rejected':
                return 'Rejected';
            default:
                return 'Unknown';
        }
    };

    // Update adjustment value
    const updateAdjustment = async (productId, field, value, event) => {

        console.log('Updating adjustment:', productId, field, value, event);
        // Show loading indicator for this cell
        cellLoading.value[productId] = {
            ...cellLoading.value[productId],
            [field]: true
        };



        // Update current adjustments
        if (!currentAdjustments.value[productId]) {
            currentAdjustments.value[productId] = {};
        }
        currentAdjustments.value[productId][field] = value;

        // If value is empty or invalid number, reset to original
        if (!value || isNaN(Number(value))) {
            currentAdjustments.value[productId][field] = null;
            cellLoading.value[productId] = {
                ...cellLoading.value[productId],
                [field]: false
            };
            return;
        }

        // Convert to number
        currentAdjustments.value[productId][field] = Number(value);

        // Update original adjustments if not set
        if (!originalAdjustments.value[productId]) {
            originalAdjustments.value[productId] = {};
        }
        if (!originalAdjustments.value[productId][field]) {
            originalAdjustments.value[productId][field] = props.reportData.find(item => item.product.id === productId)[field];
        }

        // Hide loading indicator after update
        cellLoading.value[productId] = {
            ...cellLoading.value[productId],
            [field]: false
        };

        // If Enter key is pressed, save the adjustment
        if (event.key === 'Enter') {
            await saveAdjustments(productId);
        }
    };

    // Save adjustments on Enter key press
    const saveAdjustments = async (productId) => {
        if (saving.value) return;

        const item = props.reportData.find(item => item.product.id === productId);
        if (!item) return;

        const currentAdj = currentAdjustments.value[productId];
        if (!currentAdj) return;

        const changedItem = {
            product_id: productId,
            positive_adjustment: currentAdj.positive_adjustment || item.positive_adjustment,
            negative_adjustment: currentAdj.negative_adjustment || item.negative_adjustment,
            months_of_stock: currentAdj.months_of_stock || item.months_of_stock
        };

        try {
            saving.value = true;
            const loading = Swal.fire({
                title: 'Saving adjustment...',
                allowOutsideClick: false,
                allowEscapeKey: false,
                didOpen: () => {
                    Swal.showLoading();
                }
            });

            const response = await axios.put(route('reports.warehouseMonthly.updateInventoryReportAdjustments'), {
                month_year: month_year.value,
                adjustments: [changedItem]
            });

            if (response.data.message) {
                loading.close();
                await Swal.fire(
                    'Success',
                    response.data.message,
                    'success'
                );

                // Reload data to get fresh state from server
                await reloadData();
            } else {
                loading.close();
                await Swal.fire(
                    'Error',
                    'Failed to save adjustment. Please try again.',
                    'error'
                );
            }
        } catch (error) {
            saving.value = false;
            Swal.close();
            console.error('Error saving adjustment:', error);
            await Swal.fire(
                'Error',
                error.response?.data?.message || 'Failed to save adjustment',
                'error'
            );
        } finally {
            saving.value = false;
        }
    };


    // Export to Excel
    const exportToExcel = () => {
        window.location.href = route('reports.warehouseMonthly.exportToExcel', { monthYear: month_year.value });
    };

    // Approve report
    const approveReport = async () => {
        try {
            const { isConfirmed } = await Swal.fire({
                title: 'Approve Report?',
                text: "Are you sure you want to approve this report?",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, approve it!'
            });

            if (isConfirmed) {
                const response = await axios.put(route('reports.warehouseMonthly.approve'), {
                    month_year: month_year.value
                });

                await Swal.fire(
                    'Approved!',
                    response.data.message,
                    'success'
                );

                // Refresh the page to get updated report status
                reloadData();
            }
        } catch (error) {
            console.error('Error approving report:', error);
            Swal.fire(
                'Error!',
                error.response?.data?.message || 'Failed to approve report',
                'error'
            );
        }
    };

    // Reject report
    const rejectReport = async () => {
        try {
            const { isConfirmed, value: reason } = await Swal.fire({
                title: 'Reject Report?',
                text: "Please provide a reason for rejection",
                input: 'textarea',
                inputPlaceholder: 'Enter rejection reason...',
                inputValidator: (value) => {
                    if (!value) {
                        return 'You need to provide a rejection reason';
                    }
                    return true;
                },
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#6366f1',
                confirmButtonText: 'Reject'
            });

            if (isConfirmed && reason) {
                const response = await axios.put(route('reports.warehouseMonthly.reject'), {
                    month_year: month_year.value,
                    reason: reason
                });

                await Swal.fire(
                    'Rejected!',
                    response.data.message,
                    'success'
                );

                // Refresh the page to get updated report status
                reloadData();
            }
        } catch (error) {
            console.error('Error rejecting report:', error);
            Swal.fire(
                'Error!',
                error.response?.data?.message || 'Failed to reject report',
                'error'
            );
        }
    };
</script>

   